name: 'SalesforceCI'

on: 
  push:
    branches: [dev,main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - uses: actions/setup-node@v2
        with:
          node-version: '14' 
          check-latest: true                     
      - name: Write the token into a file for Auth URL Authentication
        run: 'echo force://PlatformCLI::5Aep861NT6Ju45T6F3wrWTgUeIYszM9I0eB9iTEBbILTAmNP6dIsWf.dJ_XuIfi_ArSfF0xsjEmsBlvHwyJVV8a@dialpaddevhub1.my.salesforce.com > token.txt'
      - name: Install Salesforce CLI
        run: |
          node --version
          git --version
          npm install sfdx-cli --global
          sudo npm install sfdx-git-delta@latest -g
 
      - name: Create scratch org
        run: 'echo scratch org processed'
      
      - name: Deploy changes to Org
        run: |
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all 
          git --no-pager diff --name-status origin/${GITHUB_HEAD_REF##*/} origin/dev
          sgd --to origin/${GITHUB_REF##*/} --from origin/dev  --output .
          cat package/package.xml               
      - name: Print 
        run: |
          echo $GITHUB_REF
          echo $GITHUB_HEAD_REF
          echo $GITHUB_REF^ 
          echo "--- package.xml generated with added and modified metadata ---"
          cat package/package.xml
          echo "--- destructiveChanges.xml generated with deleted metadata ---"
          cat destructiveChanges/destructiveChanges.xml
      
      
