name: 'SalesforceCI-PullRequest'

on: 
  pull_request:
    branches: [dev,main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - uses: actions/setup-node@v2
        with:
          node-version: '14' 
          check-latest: true                     
      - name: Write the token into a file for Auth URL Authentication
        run: 'echo force://PlatformCLI::5Aep861NT6Ju45T6F3wrWTgUeIYszM9I0eB9iTEBbILTAmNP6dIsWf.dJ_XuIfi_ArSfF0xsjEmsBlvHwyJVV8a@dialpaddevhub1.my.salesforce.com > token.txt'
      - name: Install Salesforce CLI
        run: |
          node --version
          git --version
          npm install sfdx-cli --global
          sudo npm install sfdx-git-delta@latest -g
      - name: Proess Scratch org
        run: 'echo scratch org processed'
  notifySlack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: 'xoxb-2249714352531-2242775563030-UA6DjWxiUPXlwewSpt2t2VIG'
        uses: abinoda/slack-action@master
        with:
          args: '{\"channel\":\"[C0278ED8MFF]\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*The Build was job.status*\"}},{\"type\":\"divider\"},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Ref:* ${{github.ref}}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Event* : ${{github.event_name}}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Who :* ${{ github.event.pull_request.user.login }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request._links.html.href }}|View Pull Request>\"}}]}'
 

