name: 'SalesforceCI-Push'

on: 
  push:
   branches: [dev,master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
        with:
         fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: '14' 
          check-latest: true                     
      - name: Get Auth URL from secrets
        run: 'echo force://PlatformCLI::5Aep861NT6Ju45T6F3wrWTgUeIYszM9I0eB9iTEBbILTAmNP6dIsWf.dJ_XuIfi_ArSfF0xsjEmsBlvHwyJVV8a@dialpaddevhub1.my.salesforce.com > token.txt'
      - name: Install Salesforce CLI and other dependencies
        run: |
          node --version
          git --version
          npm install sfdx-cli --global
          sudo npm install sfdx-git-delta@latest -g
      - name: Authorize with DevHub
        run: 'sfdx force:auth:jwt:grant --clientid 3MVG9Nk1FpUrSQHfmKV.S7cvDKdhvM8FAfbyyfM0255yaP_20wvSYv3MkAgpj5Bsbx4VYAM.88vsPFAT7.JwO --jwtkeyfile server3.key --username raghavendra.sharma@dialpad.com.dialpaddevhub1 -a myConnectedOrg'
      - name: Prepare Delta package
        run: |
          echo $GITHUB_REF
          echo $github.ref
          echo $GITHUB_REF^ 
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all 
          git --no-pager diff --name-status $GITHUB_SHA^  $GITHUB_SHA  
          sgd --to $GITHUB_SHA --from $GITHUB_SHA^  --output . -i .forceignore
          cat package/package.xml               
      - name:  Deploy delta package to salesforce
        run: |
          echo "--- package.xml generated with added and modified metadata ---"
          cat package/package.xml
          echo "--- destructiveChanges.xml generated with deleted metadata ---"
          cat destructiveChanges/destructiveChanges.xml
          sfdx force:source:convert --outputdir mdapi_output_dir --packagename managed_pkg_name
          sfdx force:source:convert -x package/package.xml -n deltaChangeDeployment_package
          sfdx force:source:deploy  force:mdapi:deploy  - u username - d deltaChangeDeployment_package --checkonly
      
      

