name: 'SalesforceCI-PullRequest'

on: 
  pull_request:
    branches: [dev,main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - uses: actions/setup-node@v2
        with:
          node-version: '14' 
          check-latest: true                     
      - name: Write the token into a file for Auth URL Authentication
        run: 'echo force://PlatformCLI::5Aep861NT6Ju45T6F3wrWTgUeIYszM9I0eB9iTEBbILTAmNP6dIsWf.dJ_XuIfi_ArSfF0xsjEmsBlvHwyJVV8a@dialpaddevhub1.my.salesforce.com > token.txt'
      - name: Install Salesforce CLI
        run: |
          node --version
          git --version
          npm install sfdx-cli --global
          sudo npm install sfdx-git-delta@latest -g
      - name: Proess Scratch org
        run: 'echo scratch org processed'
  notifySlack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: 'xoxp-2249714352531-2255712651268-2249727486419-7e8bf35fdab9bf584d0129a991bbd23b'
        uses: abinoda/slack-action@master
        with:
          args: '{\"channel\":\"[C0278ED8MFF]\",\"text\":"Hello"}'
 

